In [10]:
%matplotlib inline
import utils; reload(utils)
from utils import *
from __future__ import division, print_function


In [11]:
def get_x(x):
    return x

In [12]:
def get_model_bn():
    model = Sequential([
        Lambda(get_x,input_shape=(3,50,50)),
        Convolution2D(32,3,3, activation='relu'),
        BatchNormalization(axis=1),
        Convolution2D(32,3,3, activation='relu'),
        MaxPooling2D(),
        BatchNormalization(axis=1),
        Convolution2D(64,3,3, activation='relu'),
        BatchNormalization(axis=1),
        Convolution2D(64,3,3, activation='relu'),
        MaxPooling2D(),
        Convolution2D(128,3,3, activation='relu'),
        BatchNormalization(axis=1),
        Convolution2D(128,3,3, activation='relu'),
        BatchNormalization(axis=1),
        MaxPooling2D(),
        Flatten(),
        BatchNormalization(),
        Dense(4096, activation='relu'),
        Dropout(0.5),
        Dense(1024, activation='relu'),
        Dropout(0.5),
        BatchNormalization(),
        Dense(43, activation='softmax')
        ])
    model.compile(Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [13]:
def get_model(i):
    model = get_model_bn()
    if(i == 0):
        model.load_weights('best5/trafficA23.h5')
    elif(i == 1):
        model.load_weights('best5/trafficB18.h5')
    elif(i == 2):
        model.load_weights('best5/trafficC19.h5')
    elif(i == 3):
        model.load_weights('best5/trafficD17.h5')
    elif(i == 4):
        model.load_weights('best5/trafficE19.h5')
    return model

In [14]:
models = [get_model(i) for i in range(5)]

/home/amitoj/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:4: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu")`
/home/amitoj/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:6: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu")`
/home/amitoj/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:9: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu")`
/home/amitoj/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:11: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu")`
/home/amitoj/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:13: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), activation="relu")`
/home/amitoj/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:15: UserWarning: Update your `Conv2D` call to the

ValueError: negative dimensions are not allowed

In [7]:
path_test = 'data/test_full/'
test_datagen = image.ImageDataGenerator()
test_generator = test_datagen.flow_from_directory(
        path_test,
        target_size=(50, 50),
        batch_size=16,
        class_mode=None,
        shuffle = False)
m0 = models[0]
p0 = m0.predict_generator(test_generator,test_generator.n)

Found 12630 images belonging to 1 classes.


In [8]:
path_test = 'data/test_full/'
test_datagen = image.ImageDataGenerator()
test_generator = test_datagen.flow_from_directory(
        path_test,
        target_size=(50, 50),
        batch_size=16,
        class_mode=None,
        shuffle = False)
m1 = models[1]
p1 = m1.predict_generator(test_generator,test_generator.n)

Found 12630 images belonging to 1 classes.


In [9]:
path_test = 'data/test_full/'
test_datagen = image.ImageDataGenerator()
test_generator = test_datagen.flow_from_directory(
        path_test,
        target_size=(50, 50),
        batch_size=16,
        class_mode=None,
        shuffle = False)
m2 = models[2]
p2 = m2.predict_generator(test_generator,test_generator.n)

Found 12630 images belonging to 1 classes.


In [10]:
path_test = 'data/test_full/'
test_datagen = image.ImageDataGenerator()
test_generator = test_datagen.flow_from_directory(
        path_test,
        target_size=(50, 50),
        batch_size=16,
        class_mode=None,
        shuffle = False)
m3 = models[3]
p3 = m3.predict_generator(test_generator,test_generator.n)

Found 12630 images belonging to 1 classes.


In [11]:
path_test = 'data/test_full/'
test_datagen = image.ImageDataGenerator()
test_generator = test_datagen.flow_from_directory(
        path_test,
        target_size=(50, 50),
        batch_size=16,
        class_mode=None,
        shuffle = False)
m4 = models[4]
p4 = m4.predict_generator(test_generator,test_generator.n)

Found 12630 images belonging to 1 classes.


In [24]:
p0_classes = np.empty([p0.shape[0]])

for j in range(p0.shape[0]):
    m = -1.
    pos = -1
    for k,l in enumerate(p0[j]):
         if(l>m):
            m = l
            pos = k
    p0_classes[j] = pos


In [25]:
p0_classes[0]

16.0

In [26]:
p1_classes = np.empty([p1.shape[0]])

for j in range(p1.shape[0]):
    m = -1.
    pos = -1
    for k,l in enumerate(p1[j]):
         if(l>m):
            m = l
            pos = k
    p1_classes[j] = pos

In [27]:
p1_classes

array([ 16.,   1.,  38., ...,   6.,   7.,  10.])

In [28]:
p2_classes = np.empty([p2.shape[0]])

for j in range(p2.shape[0]):
    m = -1.
    pos = -1
    for k,l in enumerate(p2[j]):
         if(l>m):
            m = l
            pos = k
    p2_classes[j] = pos

In [29]:
p3_classes = np.empty([p3.shape[0]])

for j in range(p3.shape[0]):
    m = -1.
    pos = -1
    for k,l in enumerate(p3[j]):
         if(l>m):
            m = l
            pos = k
    p3_classes[j] = pos

In [30]:
p4_classes = np.empty([p4.shape[0]])

for j in range(p4.shape[0]):
    m = -1.
    pos = -1
    for k,l in enumerate(p4[j]):
         if(l>m):
            m = l
            pos = k
    p4_classes[j] = pos

In [57]:
p4_classes

array([ 16.,   1.,  38., ...,   6.,   7.,  10.])

In [67]:
import scipy
mode_preds = np.empty(p4_classes.shape)
for i in  range(p0_classes.shape[0]):
    x = [p0_classes[i], p1_classes[i], p2_classes[i], p3_classes[i], p4_classes[i]]
    x_np=np.asarray(x)
    x_mode, x_count = scipy.stats.mstats.mode(x_np)
    print(x_mode)
    mode_preds[i] = x_mode

[ 16.]
[ 1.]
[ 38.]
[ 33.]
[ 11.]
[ 38.]
[ 18.]
[ 12.]
[ 25.]
[ 35.]
[ 12.]
[ 7.]
[ 23.]
[ 7.]
[ 4.]
[ 9.]
[ 21.]
[ 20.]
[ 27.]
[ 38.]
[ 4.]
[ 33.]
[ 9.]
[ 3.]
[ 1.]
[ 11.]
[ 13.]
[ 10.]
[ 9.]
[ 11.]
[ 5.]
[ 17.]
[ 34.]
[ 23.]
[ 2.]
[ 17.]
[ 3.]
[ 12.]
[ 16.]
[ 8.]
[ 7.]
[ 30.]
[ 18.]
[ 12.]
[ 24.]
[ 25.]
[ 3.]
[ 10.]
[ 18.]
[ 8.]
[ 25.]
[ 13.]
[ 15.]
[ 9.]
[ 13.]
[ 35.]
[ 5.]
[ 26.]
[ 9.]
[ 16.]
[ 38.]
[ 10.]
[ 4.]
[ 9.]
[ 15.]
[ 9.]
[ 26.]
[ 2.]
[ 5.]
[ 28.]
[ 11.]
[ 25.]
[ 30.]
[ 34.]
[ 5.]
[ 12.]
[ 1.]
[ 10.]
[ 25.]
[ 25.]
[ 21.]
[ 33.]
[ 25.]
[ 7.]
[ 10.]
[ 35.]
[ 3.]
[ 7.]
[ 22.]
[ 13.]
[ 3.]
[ 1.]
[ 2.]
[ 14.]
[ 12.]
[ 32.]
[ 3.]
[ 38.]
[ 9.]
[ 33.]
[ 1.]
[ 10.]
[ 5.]
[ 11.]
[ 33.]
[ 4.]
[ 35.]
[ 25.]
[ 33.]
[ 4.]
[ 1.]
[ 14.]
[ 16.]
[ 10.]
[ 20.]
[ 3.]
[ 27.]
[ 29.]
[ 1.]
[ 17.]
[ 13.]
[ 7.]
[ 1.]
[ 8.]
[ 2.]
[ 10.]
[ 10.]
[ 20.]
[ 1.]
[ 6.]
[ 36.]
[ 3.]
[ 14.]
[ 13.]
[ 11.]
[ 10.]
[ 18.]
[ 40.]
[ 2.]
[ 38.]
[ 41.]
[ 4.]
[ 6.]
[ 18.]
[ 17.]
[ 25.]
[ 2.]
[ 41.]
[ 11.]
[ 21.]
[ 7

In [68]:
mode_preds

array([ 16.,   1.,  38., ...,   6.,   7.,  10.])

In [69]:
np.save("preds.npy", mode_preds)